apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flaskapp
  name: flaskapp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapp
      tier: app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: flaskapp
        tier: app
    spec:
      containers:
        - name: flaskapp
          image: ankurpatel/flaskapp

          env:
            - name: FLASK_ENV
              value: "development"
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: ROOT_PASSWORD
          ports:
            - name: flaskapp
              containerPort: 5000
          resources:
            requests:
              cpu: 1G
              memory: 1Gi

      restartPolicy: Always
