apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql

spec:

# Number of Replica
  replicas: 1

# This must match the labels we set on the pod!
  selector:
    matchLabels:
      app: mysql
      tier: database

# How do want to update the pods?
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

# This template field is a regular pod configuration
  template:
    metadata:
      labels:
        app: mysql
        tier: database

# Pod configuration
    spec:
      containers:
        - name: mysql
          image: ankurpatel/kubedb:v2
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: ROOT_PASSWORD
          args: ["--default-authentication-plugin=mysql_native_password"]
          ports:
            - name: mysql
              containerPort: 3306
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping"]
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          volumeMounts:
            - name: mysql-pv
              mountPath: /tmp/mysql

# Volume configuration
      volumes:
        - name: mysql-pv
          persistentVolumeClaim:
            claimName: mysql-pvc
