apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: database
    spec:
      containers:
        -
          env:
            -
              name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: ROOT_PASSWORD
                  name: mysql-secrets
          image: "mysql:5.7"
          name: mysql
          ports:
            -
              containerPort: 3306
              name: mysql
          volumeMounts:
            -
              mountPath: /var/lib/mysql
              name: mysql-pv
      volumes:
        -
          name: mysql-pv
          persistentVolumeClaim:
            claimName: mysql-pvc
