apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mysql-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/mysql

#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  labels:
#    type: local
#  name: mysql-initdb-pv-volume
#spec:
#  accessModes:
#    - ReadWriteMany
#  capacity:
#    storage: 1Mi
#  hostPath:
#    path: /root/flaskapp_kubernetes/db/init.sql
